param(
    [string]$TaskName = "AutoDayReport-Scheduler",
    [string]$ProjectPath = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $ProjectPath)) {
    throw "Project path not found: $ProjectPath"
}

$entryPoint = Join-Path $ProjectPath "dist\scheduler.js"

if (-not (Test-Path $entryPoint)) {
    Write-Host "Building project..."
    Push-Location $ProjectPath
    try {
        npm run build
    } finally {
        Pop-Location
    }
}

if (-not (Test-Path $entryPoint)) {
    throw "Build failed: $entryPoint not found"
}

$nodePath = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $nodePath) {
    throw "Node.js not found in PATH. Please install Node.js first."
}

$configPath = Join-Path $ProjectPath "config\config.json"
$runTimeHint = "18:00"
if (Test-Path $configPath) {
    try {
        $cfg = Get-Content $configPath -Raw | ConvertFrom-Json
        if ($cfg.schedule.runTime) {
            $runTimeHint = $cfg.schedule.runTime
        }
    } catch {
        Write-Host "Warning: could not read schedule.runTime from config.json"
    }
}

$launcherVbs = Join-Path $ProjectPath "scripts\run-scheduler-hidden.vbs"
if (-not (Test-Path $launcherVbs)) {
    throw "Launcher script not found: $launcherVbs"
}

# 安装时写入带绝对路径的 launcher（任务计划 PATH 有限，且 VBS 查找 node 更稳）
$generatedVbs = Join-Path $ProjectPath "scripts\run-scheduler-launcher.vbs"
$vbsContent = @"
' Auto-generated by install-daemon.ps1 — do not edit manually
Option Explicit
Dim shell
Set shell = CreateObject("Wscript.Shell")
shell.CurrentDirectory = "$ProjectPath"
shell.Run """$nodePath"" ""$entryPoint""", 0, True
"@
Set-Content -Path $generatedVbs -Value $vbsContent -Encoding ASCII

$wscriptPath = (Get-Command wscript.exe -ErrorAction Stop).Source
$wscriptArgs = "//B //Nologo `"$generatedVbs`""

# wscript + shell.Run(0) 真正无窗口；node 是控制台程序，PowerShell Hidden 仍会出现在任务栏
$action = New-ScheduledTaskAction -Execute $wscriptPath -Argument $wscriptArgs -WorkingDirectory $ProjectPath
$trigger = New-ScheduledTaskTrigger -AtLogon
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -Hidden
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "Removing existing task: $TaskName"
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description "AutoDayReport scheduler daemon (runs at logon, executes daily per config schedule.runTime)"

Write-Host "Scheduled task '$TaskName' created successfully."
Write-Host "  Trigger: At user logon"
Write-Host "  Command: wscript //B scripts\run-scheduler-launcher.vbs"
Write-Host "  (truly hidden — no terminal icon in taskbar)"
Write-Host "  Daily run time: $runTimeHint (from config/config.json schedule.runTime)"
Write-Host ""
Write-Host "To change run time: edit config/config.json, then restart the scheduler task."
Write-Host "To run now:  schtasks /Run /TN `"$TaskName`""
Write-Host "To stop:     schtasks /End /TN `"$TaskName`""
