' Auto-generated by install-daemon.ps1 ? do not edit manually
Option Explicit
Dim shell
Set shell = CreateObject("Wscript.Shell")
shell.CurrentDirectory = "D:\program\AutoDayReport"
shell.Run """C:\Program Files\nodejs\node.exe"" ""D:\program\AutoDayReport\dist\scheduler.js""", 0, True
